# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\x12\nhelloworld\"\x07\n\x05\x45mpty\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"~\n\x0bMedicamento\x12\x16\n\x0eId_medicamento\x18\x01 \x01(\x05\x12\x0e\n\x06Numero\x18\x02 \x01(\t\x12\x11\n\tComercial\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scripcion\x18\x04 \x01(\t\x12\x0f\n\x07Id_tipo\x18\x05 \x01(\x05\x12\x0e\n\x06Nombre\x18\x06 \x01(\t\"7\n\x04Tipo\x12\x0f\n\x07Id_tipo\x18\x01 \x01(\x05\x12\x0e\n\x06\x41\x63tivo\x18\x02 \x01(\x05\x12\x0e\n\x06Nombre\x18\x03 \x01(\t\"/\n\x08Producto\x12\x13\n\x0bId_producto\x18\x01 \x01(\x05\x12\x0e\n\x06\x43odigo\x18\x02 \x01(\t\"3\n\tDatosList\x12&\n\x05\x44\x61tos\x18\x01 \x03(\x0b\x32\x17.helloworld.Medicamento\"+\n\x08TipoList\x12\x1f\n\x05Tipos\x18\x01 \x03(\x0b\x32\x10.helloworld.Tipo\"7\n\x0cProductoList\x12\'\n\tProductos\x18\x01 \x03(\x0b\x32\x14.helloworld.Producto2\xd2\x04\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x44\n\x10ListaMedicamento\x12\x17.helloworld.Medicamento\x1a\x15.helloworld.DatosList\"\x00\x12\x44\n\x0f\x41ltaMedicamento\x12\x17.helloworld.Medicamento\x1a\x16.helloworld.HelloReply\"\x00\x12\x36\n\x08\x41ltaTipo\x12\x10.helloworld.Tipo\x1a\x16.helloworld.HelloReply\"\x00\x12:\n\x0c\x45liminarTipo\x12\x10.helloworld.Tipo\x1a\x16.helloworld.HelloReply\"\x00\x12\x35\n\tListaTipo\x12\x10.helloworld.Tipo\x1a\x14.helloworld.TipoList\"\x00\x12@\n\x13\x42uscarMedicamentoId\x12\x10.helloworld.Tipo\x1a\x15.helloworld.DatosList\"\x00\x12K\n\x17\x42uscarMedicamentoNombre\x12\x17.helloworld.Medicamento\x1a\x15.helloworld.DatosList\"\x00\x12\x41\n\rListaProducto\x12\x14.helloworld.Producto\x1a\x18.helloworld.ProductoList\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='helloworld.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='helloworld.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=69,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='helloworld.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=100,
)


_MEDICAMENTO = _descriptor.Descriptor(
  name='Medicamento',
  full_name='helloworld.Medicamento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id_medicamento', full_name='helloworld.Medicamento.Id_medicamento', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Numero', full_name='helloworld.Medicamento.Numero', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Comercial', full_name='helloworld.Medicamento.Comercial', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Descripcion', full_name='helloworld.Medicamento.Descripcion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Id_tipo', full_name='helloworld.Medicamento.Id_tipo', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Nombre', full_name='helloworld.Medicamento.Nombre', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=228,
)


_TIPO = _descriptor.Descriptor(
  name='Tipo',
  full_name='helloworld.Tipo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id_tipo', full_name='helloworld.Tipo.Id_tipo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Activo', full_name='helloworld.Tipo.Activo', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Nombre', full_name='helloworld.Tipo.Nombre', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=285,
)


_PRODUCTO = _descriptor.Descriptor(
  name='Producto',
  full_name='helloworld.Producto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id_producto', full_name='helloworld.Producto.Id_producto', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Codigo', full_name='helloworld.Producto.Codigo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=334,
)


_DATOSLIST = _descriptor.Descriptor(
  name='DatosList',
  full_name='helloworld.DatosList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Datos', full_name='helloworld.DatosList.Datos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=387,
)


_TIPOLIST = _descriptor.Descriptor(
  name='TipoList',
  full_name='helloworld.TipoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Tipos', full_name='helloworld.TipoList.Tipos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=432,
)


_PRODUCTOLIST = _descriptor.Descriptor(
  name='ProductoList',
  full_name='helloworld.ProductoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Productos', full_name='helloworld.ProductoList.Productos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=489,
)

_DATOSLIST.fields_by_name['Datos'].message_type = _MEDICAMENTO
_TIPOLIST.fields_by_name['Tipos'].message_type = _TIPO
_PRODUCTOLIST.fields_by_name['Productos'].message_type = _PRODUCTO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Medicamento'] = _MEDICAMENTO
DESCRIPTOR.message_types_by_name['Tipo'] = _TIPO
DESCRIPTOR.message_types_by_name['Producto'] = _PRODUCTO
DESCRIPTOR.message_types_by_name['DatosList'] = _DATOSLIST
DESCRIPTOR.message_types_by_name['TipoList'] = _TIPOLIST
DESCRIPTOR.message_types_by_name['ProductoList'] = _PRODUCTOLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Empty)
  })
_sym_db.RegisterMessage(Empty)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

Medicamento = _reflection.GeneratedProtocolMessageType('Medicamento', (_message.Message,), {
  'DESCRIPTOR' : _MEDICAMENTO,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Medicamento)
  })
_sym_db.RegisterMessage(Medicamento)

Tipo = _reflection.GeneratedProtocolMessageType('Tipo', (_message.Message,), {
  'DESCRIPTOR' : _TIPO,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Tipo)
  })
_sym_db.RegisterMessage(Tipo)

Producto = _reflection.GeneratedProtocolMessageType('Producto', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTO,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Producto)
  })
_sym_db.RegisterMessage(Producto)

DatosList = _reflection.GeneratedProtocolMessageType('DatosList', (_message.Message,), {
  'DESCRIPTOR' : _DATOSLIST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.DatosList)
  })
_sym_db.RegisterMessage(DatosList)

TipoList = _reflection.GeneratedProtocolMessageType('TipoList', (_message.Message,), {
  'DESCRIPTOR' : _TIPOLIST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.TipoList)
  })
_sym_db.RegisterMessage(TipoList)

ProductoList = _reflection.GeneratedProtocolMessageType('ProductoList', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTOLIST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ProductoList)
  })
_sym_db.RegisterMessage(ProductoList)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=492,
  serialized_end=1086,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='helloworld.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListaMedicamento',
    full_name='helloworld.Greeter.ListaMedicamento',
    index=1,
    containing_service=None,
    input_type=_MEDICAMENTO,
    output_type=_DATOSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AltaMedicamento',
    full_name='helloworld.Greeter.AltaMedicamento',
    index=2,
    containing_service=None,
    input_type=_MEDICAMENTO,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AltaTipo',
    full_name='helloworld.Greeter.AltaTipo',
    index=3,
    containing_service=None,
    input_type=_TIPO,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EliminarTipo',
    full_name='helloworld.Greeter.EliminarTipo',
    index=4,
    containing_service=None,
    input_type=_TIPO,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListaTipo',
    full_name='helloworld.Greeter.ListaTipo',
    index=5,
    containing_service=None,
    input_type=_TIPO,
    output_type=_TIPOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BuscarMedicamentoId',
    full_name='helloworld.Greeter.BuscarMedicamentoId',
    index=6,
    containing_service=None,
    input_type=_TIPO,
    output_type=_DATOSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BuscarMedicamentoNombre',
    full_name='helloworld.Greeter.BuscarMedicamentoNombre',
    index=7,
    containing_service=None,
    input_type=_MEDICAMENTO,
    output_type=_DATOSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListaProducto',
    full_name='helloworld.Greeter.ListaProducto',
    index=8,
    containing_service=None,
    input_type=_PRODUCTO,
    output_type=_PRODUCTOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
